# Default production environment Dockerfile
FROM node:18-alpine


WORKDIR /app

COPY package.json ./

RUN npm install

# Copy the rest of the application code
COPY . .


# Define ARGs for each of your Firebase environment variables
ARG VITE_FIREBASE_AKEY_ID
ARG VITE_FIREBASE_AUTHDOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_ENDPOINT_API
ARG VITE_USER_QUEUE_REGISTRATION
ARG VITE_USER_QUEUE_REGISTRATION_KEY
ARG VITE_SEC_ALGORITHM
ARG VITE_SEC_HASH
ARG VITE_SEC_KEY_SIZE
ARG VITE_SEC_ITERATION_COUNT



# Pass ARG values to the build process
ENV VITE_FIREBASE_AKEY_ID=${VITE_FIREBASE_AKEY_ID}
ENV VITE_FIREBASE_AUTHDOMAIN=${VITE_FIREBASE_AUTHDOMAIN}
ENV VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
ENV VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
ENV VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
ENV VITE_ENDPOINT_API=${VITE_ENDPOINT_API}
ENV VITE_USER_QUEUE_REGISTRATION=${VITE_USER_QUEUE_REGISTRATION}
ENV VITE_USER_QUEUE_REGISTRATION_KEY=${VITE_USER_QUEUE_REGISTRATION_KEY}
ENV VITE_SEC_ALGORITHM=${VITE_SEC_ALGORITHM}
ENV VITE_SEC_HASH=${VITE_SEC_HASH}
ENV VITE_SEC_KEY_SIZE=${VITE_SEC_KEY_SIZE}
ENV VITE_SEC_ITERATION_COUNT=${VITE_SEC_ITERATION_COUNT}

RUN npm run build

EXPOSE 5173

# Use Vite's preview server to serve the built files
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]