[build]
builder = "NIXPACKS"
command = "npm install && npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[static]
directory = "dist"
serve = true
